language: ruby
cache: bundler
os: linux
dist: xenial
rvm:
  - 2.7.3
sudo: false # route your build to the container-based infrastructure for a faster build
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
 - sudo apt-get -q update
 - sudo apt-get -y install libcurl4-openssl-dev
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --url-swap '^/klangturm/:/' --assume-extension ./_site
  - :>_site/.nojekyll # disable jekyll processing on github pages

deploy:
  # deploy main onto github pages
  - provider: pages
    local_dir: _site # publish static page only
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: main
  # deploy main to live via Plesk git method
  - provider: git_push
    local_dir: _site # publish static page only
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    commit_message: "Deploy %{project_name} to %{url}:%{target_branch}"
    base_branch: gh-pages
    branch: live
    cleanup: false
    on:
      all_branches: true # just for testing
      # branch: main
