language: ruby
rvm:
  - 2.7.3
sudo: false # route your build to the container-based infrastructure for a faster build
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
    - curl
    - unzip
    - moreutils

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --url-swap '^/klangturm/:/' --assume-extension ./_site
  - :>_site/.nojekyll # disable jekyll processing on github pages

deploy:
  # deploy main onto github pages
  - provider: pages
    local_dir: _site # publish static page only
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: main
  # deploy main to live (ftp)
  - provider: script
    script: bash scripts/deploy.sh
    on:
      all_branches: true # just for testing
      # branch: main
