language: ruby
cache: bundler
os: linux
dist: xenial
rvm:
  - 2.7.3
sudo: false # route your build to the container-based infrastructure for a faster build
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
 - sudo apt-get -q update
 - sudo apt-get -y install libcurl4-openssl-dev curl unzip moreutils
 - |-
   echo "deb https://deb.torproject.org/torproject.org/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/tor.list
   curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | sudo gpg --import
   sudo gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
   sudo apt-get -q update
   sudo apt install tor tor-geoipdb torsocks deb.torproject.org-keyring
 - |-
   export GRAFTCP_URL='https://github.com/hmgle/graftcp/releases/download/v0.3.1/graftcp_0.3.1-1_amd64.deb'
   curl -L $GRAFTCP_URL > /tmp/graftcp.deb
   sudo dpkg -i /tmp/graftcp.deb
   sudo apt-get -y install -f
 - >
   echo "socks5 = 127.0.0.1:9050" | sudo tee -a /etc/graftcp-local/graftcp-local.conf
 - |-
   cat /etc/graftcp-local/graftcp-local.conf
   sudo systemctl enable graftcp-local
   sudo systemctl start graftcp-local
   sudo systemctl status graftcp-local
 - |-
   curl https://rclone.org/install.sh | sudo bash

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --url-swap '^/klangturm/:/' --assume-extension ./_site
  - :>_site/.nojekyll # disable jekyll processing on github pages

deploy:
  # deploy main onto github pages
  - provider: pages
    local_dir: _site # publish static page only
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: main
  # deploy main to live (ftp)
  - provider: script
    script: bash scripts/deploy.sh
    edge: true
    cleanup: false
    on:
      all_branches: true # just for testing
      # branch: main
