language: ruby
cache: bundler
rvm:
  - 2.6
script: "bundle exec jekyll build"
deploy:
  provider: pages
  local_dir: _site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
