# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Klangturm Hamburg-Veddel
email: klangturm.hamburg.veddel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hier befindet sich der Klangturm Hamburg-Veddel:
  https://www.google.de/maps/place/Wilhelmsburger+Str.+73,+20539+Hamburg/@53.5253632,10.01535,17z/data=!3m1!4b1!4m5!3m4!1s0x47b18e5d1b016a53:0x5d7d5de31e01d4d8!8m2!3d53.5253632!4d10.0175387
baseurl: "/klangturm" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
