# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Klangturm Hamburg-Veddel
email: klangturm.hamburg.veddel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hamburg hat jetzt einen Klangturm und er steht im zentrumsnahen und vielfach außergewöhnlichen Stadtteil Veddel. Im 1952 wiederaufgebauten Turm der ev.-luth. Immanuelkirche läuten keine Glocken mehr, jetzt ertönen Klänge aus Lautsprechern.
  Die Klangprogramme von 12 Künstler*innen und einer Schulklasse dienen wie Glockenschläge der Signalisierung der Uhrzeit.
  Es nehmen teil: Andrew Pekler (Berlin), Nika Son (Hamburg), Félicia Atkinson (Paris), Hans Schüttler (Hamburg), Tintin Patrone (Hamburg), Derya Yildirim (Berlin), Frank Bretschneider (Berlin), AtomTM (Santiago de Chile), Dave Wheels (London), Even Tuell (Kleestadt), Midori Takada (Tokio), Olaf Nicolai (Berlin) sowie Kinder einer Musikklasse der Schule auf der Veddel.
  Zu hören sind die Klänge vom 01.07.2021 bis 31.07.2022 täglich außer montags jeweils von 8 bis 20 Uhr im Viertelstundentakt.
  Das Projekt wird unterstützt vom Verfügungsfonds des Stadtteilbeirats Hamburg-Veddel, dem Musikfonds e.V. sowie der Gwärtler-Stiftung.  
baseurl: "/klangturm" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
